version: '3.9'
services:
  web:
    networks:
      - mikhailichenko
    environment:
      - LOG_FILE=/logs/log.log
    build:
      context: .
      dockerfile: docker/DockerfileForCompose
    ports:
      - "80:80"
    volumes:
      - .:/srv
      - ./logs:/logs

networks:
  mikhailichenko:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.8.0/24
          gateway: 10.20.8.1